# generated by fastapi-codegen:
#   filename:  swagger.yaml
#   timestamp: 2020-11-01T14:27:28+00:00

from __future__ import annotations

from fastapi import FastAPI

from .models import Time

try:
    from .implementation import Implementation

    implementation = Implementation()
except ModuleNotFoundError as e:
    raise NotImplementedError

app = FastAPI(
    title="Basket",
    description="REST API doc for Basket.",
    contact="{'email': 'akuma5157@gmail.com'}",
    version="0.1",
)


@app.get('/time/', response_model=Time)
def get_time() -> Time:
    return implementation.get_time()
