# generated by datamodel-codegen:
#   filename:  swagger.yaml
#   timestamp: 2020-11-01T14:27:28+00:00

from typing import Optional

from pydantic import BaseModel


class Time(BaseModel):
    __root__: str


class ApiResponse(BaseModel):
    code: Optional[int] = None
    type: Optional[str] = None
    message: Optional[str] = None
