# generated by datamodel-codegen:
#   filename:  ../swagger.yaml
#   timestamp: 2020-11-03T21:13:41+00:00

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class Value(BaseModel):
    entity_type: Optional[str] = None
    value: Optional[str] = None


class SlotValidationNumericRequest(BaseModel):
    invalid_trigger: Optional[str] = None
    key: Optional[str] = None
    name: Optional[str] = None
    reuse: Optional[bool] = None
    pick_first: Optional[bool] = False
    support_multiple: Optional[bool] = True
    type: Optional[List[str]] = None
    validation_parser: Optional[str] = None
    constraint: Optional[str] = None
    var_name: Optional[str] = None
    values: Optional[List[Value]] = None


class SlotValidationFiniteValuesRequest(BaseModel):
    invalid_trigger: Optional[str] = None
    key: Optional[str] = None
    name: Optional[str] = None
    reuse: Optional[bool] = None
    support_multiple: Optional[bool] = True
    pick_first: Optional[bool] = False
    supported_values: Optional[List[str]] = None
    type: Optional[List[str]] = None
    validation_parser: Optional[str] = None
    values: Optional[List[Value]] = None


class SlotValidationResult(BaseModel):
    filled: Optional[bool] = None
    partially_filled: Optional[bool] = None
    trigger: Optional[str] = None
    parameters: Optional[Dict[str, Any]] = None


class Time(BaseModel):
    __root__: str


class ApiResponse(BaseModel):
    code: Optional[int] = None
    type: Optional[str] = None
    message: Optional[str] = None
