/**
 * Basket
 * REST API doc for Basket.
 *
 * OpenAPI spec version: 0.1
 * Contact: akuma5157@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Time = string;