# generated by fastapi-codegen:
#   filename:  swagger.yaml
#   timestamp: 2020-10-31T14:03:29+00:00

from __future__ import annotations

from fastapi import FastAPI

from models import Time

app = FastAPI()


@app.get('/time/', response_model=Time)
def get_time() -> Time:
    pass
